### ISSUE TITLE
Authenticate to staging repo?

### ISSUE THREAD

**Issue by joshma** [signalfx/phabricator-circleci#1]
Hey there, thanks for making this! I realize this is probably not intended for others to use yet, but I thought I'd give a shot at it. I'm currently trying to figure out how to auth the container to clone from the staging repo - is there some trick for doing this?

**Comment by cep21** [comment]
Yes.  We cross mounted into the docker container the directory /root/.ssh (inside the container) to /storage/staging_repo and put inside /storage/staging_repo a .ssh key that allowed access to the staging repository on github.

**Comment by joshma** [comment]
Awesome, thanks! While you're here...did you folks use API Gateway for the HTTP endpoint? Can you share the mapping template you're using? Trying to guess from the golang code but confused by some pieces (e.g. do I need "allParamsJson => "header" to be filled out?)

**Comment by cep21** [comment]
> did you folks use API Gateway for the HTTP endpoint

Yeap.

Content-Type: application/json
Content-Type: application/x-www-form-urlencoded

Both at 

```
#set($params = $input.params())
{
    "formparams" : $input.json('$'),
    "allParamsJson" : {
    #foreach($type in $params.keySet())
    "$type" : {
            #foreach($paramName in $params.get($type).keySet())
                "$paramName" : "$util.escapeJavaScript($params.get($type).get($paramName))"
                #if($foreach.hasNext),
                #end
            #end
        }
    #if($foreach.hasNext),
    #end
    #end
    }
}
```

**Comment by joshma** [comment]
awesome, thanks so much for your help!
